openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                users:
                  - last_name: "Smith"
                    first_name: "Ferdinand"
                    email: "f.smith@example.com"
                    id: 1
                  - last_name: "Jones"
                    first_name: "Jill"
                    email: "j.jones@example.com"
                    id: 2
                  - last_name: "Martinez"
                    first_name: "Marty"
                    email: "m.martinez@example.com"
                    id: 3
                  - last_name: "Bailey"
                    first_name: "Bill"
                    email: "b.bailey@example.com"
                    id: 4

    post:
      summary: Add a user
      requestBody:
        required: true
        content:
          application/json:
            example:
              last_name: "Doe"
              first_name: "John"
              email: "j.doe@example.com"
      responses:
        '201':
          description: User added successfully
          content:
            application/json:
              example:
                id: 5
                last_name: "Doe"
                first_name: "John"
                email: "j.doe@example.com"

  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                last_name: "Smith"
                first_name: "Ferdinand"
                email: "f.smith@example.com"
                id: 1

    patch:
      summary: Update a property of a user (excluding ID)
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "new.email@example.com"
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                last_name: "Smith"
                first_name: "Ferdinand"
                email: "new.email@example.com"
                id: 1

    delete:
      summary: Delete a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '204':
          description: User deleted successfully

  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                tasks:
                  - user_id: 1
                    title: "Grocery shopping"
                    description: "eggs, bacon, gummy bears"
                    due_date: "2024-02-20T17:00"
                    warning: "-10"
                    id: 1
                  - user_id: 1
                    title: "Piano recital"
                    description: "Daughter's first concert appearance"
                    due_date: "2024-04-02T15:00"
                    warning: "-30"
                    id: 2
                  - user_id: 2
                    title: "Oil change"
                    description: "5K auto service"
                    due_date: "2024-03-10T09:00"
                    warning: "-60"
                    id: 3
                  - user_id: 3
                    title: "Get shots for dog"
                    description: "Annual vaccinations for poochy"
                    due_date: "2024-05-11T14:00"
                    warning: "-20"
                    id: 4

    post:
      summary: Add a task
      requestBody:
        required: true
        content:
          application/json:
            example:
              user_id: 1
              title: "New Task"
              description: "Description of the new task"
              due_date: "2024-06-01T12:00"
              warning: "-5"
      responses:
        '201':
          description: Task added successfully
          content:
            application/json:
              example:
                id: 5
                user_id: 1
                title: "New Task"
                description: "Description of the new task"
                due_date: "2024-06-01T12:00"
                warning: "-5"

  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                user_id: 1
                title: "Grocery shopping"
                description: "eggs, bacon, gummy bears"
                due_date: "2024-02-20T17:00"
                warning: "-10"
                id: 1

    patch:
      summary: Update a property of a task (excluding ID)
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              description: "Updated description"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              example:
                user_id: 1
                title: "Grocery shopping"
                description: "Updated description"
                due_date: "2024-02-20T17:00"
                warning: "-10"
                id: 1

    delete:
      summary: Delete a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID of the task
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully